export const PetParentFormSchema = (providerOptions: { label: string; value: string }[] = [], chargecodeOptions: { label: string; value: string }[] = [], setslotoptions: { label: string; value: string }[] = []
    , parentOptions: { label: string; value: string }[] = [], petOptions: { label: string; value: string }[] = []
) => ({
    title: "PetParent Form",
    fields: [
        {
            name: "firstName",
            label: "FirstName",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "FirstName",
            required: true,
        },
        {
            name: "lastname",
            label: "LastName",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "LastName",
            required: true,
        },
        {
            name: "mobilenumber",
            label: "MobileNumber",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "MobileNumber",
            required: true,
        },
        {
            name: "email",
            label: "Email",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Email",
            required: true,
        },
        {
            name: "userName",
            label: "UserName",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "UserName",
            required: true,
        },
        {
            name: "password",
            label: "Password",
            type: "textarea",
            fieldType: "textarea",
            required: true,
        },
        {
            name: "confirmpassword",
            label: "Confirm Password",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Confirm Password",
            required: true,
        },
        {
            name: "address1",
            label: "Address 1",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Address 1",
            required: false,
        },
        {
            name: "address2",
            label: "Address 2",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Address 2",
            required: false,
        },
        {
            name: "city",
            label: "City",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "City",
            required: false,
        },
        {
            name: "country",
            label: "Country",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Country",
            required: false,
        },
        {
            name: "state",
            label: "State",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "State",
            required: false,
        },
        {
            name: "zipcode",
            label: "Zipcode",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Zipcode",
            required: false,
        },
        {
            name: "timezone",
            label: "Time Zone",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Time Zone",
            required: false,
        },
        {
            name: "status",
            label: "Status",
            type: "textarea",
            fieldType: "textarea",
            placeholder: "Status",
            required: true,
        },
    ]
});
